// Generated by sqltyper from find-users-by-programming-language.sql.
// Do not edit directly. Instead, edit find-users-by-programming-language.sql and re-run sqltyper.


import * as pgp from 'pg-promise'

export async function findUsersByProgrammingLanguage(
  client: pgp.IDatabase<any, any>, params: { lang: string }
): Promise<Array<{ 'id': number; 'username': string | null; 'name': string | null; 'location': string | null; 'followers': number | null; 'following': number | null; 'programming_language': string }>> {
    const result = await client.query(`\
SELECT * FROM users WHERE programming_language = $1;`, [ params.lang ])
    return result
}
