// Generated by sqltyper from find-users-by-location.sql.
// Do not edit directly. Instead, edit find-users-by-location.sql and re-run sqltyper.


import * as pgp from 'pg-promise'

export async function findUsersByLocation(
  client: pgp.IDatabase<any, any>, params: { location: string }
): Promise<Array<{ 'id': number; 'username': string | null; 'name': string | null; 'location': string; 'followers': number | null; 'following': number | null; 'programming_language': string | null }>> {
    const result = await client.query(`\
SELECT * FROM users WHERE location = $1;`, [ params.location ])
    return result
}
