// Generated by sqltyper from insert-user.sql.
// Do not edit directly. Instead, edit insert-user.sql and re-run sqltyper.


import * as pgp from 'pg-promise'

export async function insertUser(
  client: pgp.IDatabase<any, any>, params: { login: string | null, name: string | null, location: string | null, followers: number | null, following: number | null, language: string | null }
): Promise<{ 'name': string | null; 'location': string | null }> {
    const result = await client.query(`\
INSERT INTO users(username, name, location, followers, following, programming_language)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING name, location;`, [ params.login, params.name, params.location, params.followers, params.following, params.language ])
    return result[0]
}
