// Generated by sqltyper from select-user.sql.
// Do not edit directly. Instead, edit select-user.sql and re-run sqltyper.


import * as pgp from 'pg-promise'

export async function selectUser(
  client: pgp.IDatabase<any, any>
): Promise<Array<{ 'id': number; 'username': string | null; 'name': string | null; 'location': string | null; 'followers': number | null; 'following': number | null; 'programming_language': string | null }>> {
    const result = await client.query(`\
SELECT * FROM users;`)
    return result
}
