// Generated by sqltyper from update-user-language.sql.
// Do not edit directly. Instead, edit update-user-language.sql and re-run sqltyper.


import * as pgp from 'pg-promise'

export async function updateUserLanguage(
  client: pgp.IDatabase<any, any>, params: { language: string | null, id: number }
): Promise<Array<{ 'id': number; 'username': string | null; 'name': string | null; 'location': string | null; 'followers': number | null; 'following': number | null; 'programming_language': string | null }>> {
    const result = await client.query(`\
UPDATE users SET programming_language = $1 WHERE id = $2
RETURNING *;`, [ params.language, params.id ])
    return result
}
